# Generated by Django 4.1.2 on 2022-10-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
